version: '2'

services:

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: unless-stopped

  web:
    build: .
    command: '.docker/run.sh'
    environment:
      POSTGRES_HOST: 'postgres'
    expose:
      - '8000'
    links:
      - postgres
    ports:
      - '8000:8000'
    restart: unless-stopped
    volumes:
      - '.:/src'
